version: "3.8"

services:

  service1:
    image: service1:latest
    build: ./service1
    container_name: service1
    ports: 
      - 8080:8080

  service2:
    image: service2:latest
    build: ./service2
    container_name: service2
    ports:
      - 8081:8080