service:
  image:
    repository: flesnjakovic/service1
    pullPolicy: Always
    tag: 0.0.1

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  deploymentAnnotations: {}

  service:
    type: ClusterIP
    port: 8080

  resources:
    requests:
      cpu: 0.2
      memory: 256Mi
    limits:
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 65
    # targetMemoryUtilizationPercentage: 80

  # This will end up inside configmap. Not encrypted at rest.
  config:
