{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-config
data:
  {{- range $key, $value := .Values.config }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end }}